import Head from "next/head";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import MangasSection from "../components/MangasSection/MangasSection";
import type { NextPage } from "next";
import { AnilistManga } from "./manga/types/types";
import { useUserStore } from "../features/zustand/store";
import { handleFetchManga } from "../api/anilistApi";

type FetchedMangas = {
  manga: {
    data: {
      Page: {
        media: AnilistManga[];
      };
    };
  };
};

const Home: NextPage<FetchedMangas> = (props: FetchedMangas) => {
  const { user } = useUserStore();

  return (
    <div className={styles.container}>
      <Head>
        <title>Manilist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      {user?.list && <MangasSection props={user!.list} header="Currently reading" />}
      <MangasSection props={props.manga.data.Page.media} header="Top rated" />
    </div>
  );
};

export const getServerSideProps = async () => {
  const mangas = await handleFetchManga();

  return {
    props: {
      manga: mangas,
    },
  };
};

export default Home;
