import Head from "next/head";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import MangasSection from "../components/MangasSection/MangasSection";
import type { NextPage } from "next";
import { AnilistManga } from "./manga/types/types";
import { useUserStore } from "../features/zustand/store";
import { handleFetchCurrentUser, handleFetchManga } from "../api/anilistApi";
import { useQuery } from "react-query";
import useAuth from "../features/user/hooks/useAuth";
import { useEffect } from "react";

type FetchedMangas = {
  manga: {
    data: {
      Page: {
        media: AnilistManga[];
      };
    };
  };
};

const Home: NextPage<FetchedMangas> = (props: FetchedMangas) => {
  const { auth } = useAuth();
  const { handleLoginUser } = useUserStore();
  const { data: user } = useQuery(
    ["user"],
    () => {
      return handleFetchCurrentUser(auth);
    },
    { enabled: !!auth }
  );

  useEffect(() => {
    user && handleLoginUser(user);
  }, [user]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Manilist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      {user && (
        <>
          <MangasSection props={user!.list.current} header="Currently reading" />
          <MangasSection props={user!.list.planning} header="Planning to read" />
        </>
      )}
      <MangasSection props={props.manga.data.Page.media} header="Top rated" />
    </div>
  );
};

export const getServerSideProps = async () => {
  const mangas = await handleFetchManga();

  return {
    props: {
      manga: mangas,
    },
  };
};

export default Home;
